# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abosch <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/23 23:00:37 by abosch            #+#    #+#              #
#    Updated: 2018/07/24 22:37:07 by abosch           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: doop

doop:
	gcc -o do-op main.c add.c minus.c divid.c multi.c mod.c do_op.c atoi.c putnbr.c putstr.c put_char.c

clean :
	rm -f do-op

re: clean all
